import { describe, expect, it } from 'vitest'

import { generateModelTypes } from './codegen.js'
import type { PrismaModel } from './dmmf.js'

const models = (...defs: Array<[string, (string | undefined)?, (string[] | undefined)?]>): readonly PrismaModel[] =>
  defs.map(([name, tableName, columns]) =>
    Object.freeze({ name, tableName: tableName ?? name, columns: Object.freeze(columns ?? []) })
  )

describe('generateModelTypes', () => {
  it('emits Models const + ModelName type + ModelTables const', () => {
    const out = generateModelTypes(models(['Workbench'], ['Workspace']))
    expect(out).toContain('export const Models = {')
    expect(out).toContain("Workbench: 'Workbench',")
    expect(out).toContain("Workspace: 'Workspace',")
    expect(out).toContain('export type ModelName = (typeof Models)[keyof typeof Models]')
    expect(out).toContain('export const ModelTables = {')
  })

  it('sorts models alphabetically for deterministic diffs', () => {
    const out = generateModelTypes(models(['Zoo'], ['Apple'], ['Middle']))
    const applePos = out.indexOf('Apple:')
    const middlePos = out.indexOf('Middle:')
    const zooPos = out.indexOf('Zoo:')
    expect(applePos).toBeLessThan(middlePos)
    expect(middlePos).toBeLessThan(zooPos)
  })

  it('preserves @@map-resolved table names in ModelTables', () => {
    const out = generateModelTypes(models(['User', 'app_user_account']))
    expect(out).toContain("User: 'app_user_account',")
  })

  it('falls back to the model name when no @@map override is supplied', () => {
    const out = generateModelTypes(models(['Workbench']))
    expect(out).toContain("Workbench: 'Workbench',") // in ModelTables too
  })

  it('handles empty models list with empty consts + never ModelName', () => {
    const out = generateModelTypes([])
    expect(out).toContain('export const Models = {} as const')
    expect(out).toContain('export type ModelName = never')
    expect(out).toContain('export const ModelTables = {} as const')
    expect(out).toContain('export const ModelColumns = {} as const')
    expect(out).toContain('export type GuarddogModels =')
  })

  it('emits ModelColumns + GuarddogModels with per-model columns from dbName', () => {
    const out = generateModelTypes(models(['Workspace', undefined, ['id', 'tenantId', 'name']]))
    expect(out).toContain('export const ModelColumns = {')
    expect(out).toContain("  Workspace: ['id', 'tenantId', 'name'],")
    expect(out).toContain('export type GuarddogModels = { readonly [K in keyof typeof ModelColumns]')
  })

  it('emits an empty column tuple for a model with no columns', () => {
    const out = generateModelTypes(models(['Empty', undefined, []]))
    expect(out).toContain('  Empty: [],')
  })

  it('uses default header marking the file as generated', () => {
    const out = generateModelTypes(models(['X']))
    expect(out).toMatch(/auto-generated by prisma-guarddog/)
    expect(out).toMatch(/Do not edit manually/)
  })

  it('honors a custom header', () => {
    const out = generateModelTypes(models(['X']), { header: '// custom header\n' })
    expect(out.startsWith('// custom header\n')).toBe(true)
    expect(out).not.toMatch(/auto-generated by prisma-guarddog/)
  })

  it('output is deterministic across repeated calls', () => {
    const m = models(['A'], ['B'], ['C'])
    expect(generateModelTypes(m)).toBe(generateModelTypes(m))
  })
})
