/**
 * Generate the DMMF-bridged model-name types that consumers import into
 * their guarddog schema file:
 *
 *     // generated by `prisma-guarddog generate` (or the Prisma
 *     // generator-block hook, when wired)
 *     export const Models = {
 *       Workbench: 'Workbench',
 *       Workspace: 'Workspace',
 *       ...
 *     } as const
 *
 *     export type ModelName = (typeof Models)[keyof typeof Models]
 *
 *     export const ModelTables = {
 *       Workbench: 'workbench',
 *       Workspace: 'workspaces',  // @@map override
 *       ...
 *     } as const
 *
 *     export const ModelColumns = {
 *       Workbench: ['id', 'ownerId', 'workspaceId'],
 *       Workspace: ['id', 'name', 'tenantId'],
 *       ...
 *     } as const
 *
 *     export type GuarddogModels = { readonly [K in keyof typeof ModelColumns]: (typeof ModelColumns)[K][number] }
 *
 * Consumers then write `guard.model(Models.Workbench)` and get autocomplete
 * + type-checked model names that always reflect the current
 * `schema.prisma`. ModelTables is bridge data for the emitter's
 * table-name resolver when consumers want to feed it from DMMF rather than
 * the default snake_case heuristic. `ModelColumns` (model -> SQL columns,
 * from DMMF `dbName`) is passed to `defineSchema({ models: ModelColumns })`
 * to power typed `model()` + `p.col(...)` (ADR-0028) — inferred, no explicit
 * generic.
 *
 * Pure code generation — no filesystem. The CLI's `writeModelTypes`
 * wrapper handles the disk write.
 */

import { writeFile } from 'node:fs/promises'

import type { PrismaModel } from './dmmf.js'

export interface CodegenOptions {
  /**
   * Header comment block prepended to the generated file. Defaults to a
   * "do not edit; regenerate via prisma-guarddog generate" notice.
   */
  readonly header?: string
}

const DEFAULT_HEADER = [
  '// This file is auto-generated by prisma-guarddog. Do not edit manually.',
  '// Regenerate via `prisma-guarddog generate`, or via `prisma generate`',
  '// when the `generator guarddog` block is wired in your `schema.prisma`.',
  '',
].join('\n')

/**
 * Render the Models / ModelName / ModelTables source from a parsed model
 * list. Pure function — deterministic given the same inputs (models are
 * sorted alphabetically before emission so commit diffs stay clean).
 */
export function generateModelTypes(models: readonly PrismaModel[], opts: CodegenOptions = {}): string {
  const header = opts.header ?? DEFAULT_HEADER

  const guarddogModelsType =
    '/** Prisma model -> its SQL column-name union (DMMF dbName). Powers typed `p.col(...)`. */\n' +
    'export type GuarddogModels = { readonly [K in keyof typeof ModelColumns]: (typeof ModelColumns)[K][number] }'

  if (models.length === 0) {
    return [
      header,
      'export const Models = {} as const',
      '',
      'export type ModelName = never',
      '',
      'export const ModelTables = {} as const',
      '',
      '/** Prisma model -> its SQL columns (DMMF dbName). Pass to `defineSchema({ models: ModelColumns })`. */',
      'export const ModelColumns = {} as const',
      '',
      guarddogModelsType,
      '',
    ].join('\n')
  }

  const sorted = [...models].toSorted((a, b) => a.name.localeCompare(b.name))
  const modelLines = sorted.map((m) => `  ${m.name}: '${m.name}',`).join('\n')
  const tableLines = sorted.map((m) => `  ${m.name}: '${m.tableName}',`).join('\n')
  const columnLines = sorted.map((m) => `  ${m.name}: [${m.columns.map((c) => `'${c}'`).join(', ')}],`).join('\n')

  return [
    header,
    'export const Models = {',
    modelLines,
    '} as const',
    '',
    'export type ModelName = (typeof Models)[keyof typeof Models]',
    '',
    '/** Prisma model -> resolved table name (post-`@@map`). */',
    'export const ModelTables = {',
    tableLines,
    '} as const',
    '',
    '/** Prisma model -> its SQL columns (DMMF dbName). Pass to `defineSchema({ models: ModelColumns })`. */',
    'export const ModelColumns = {',
    columnLines,
    '} as const',
    '',
    guarddogModelsType,
    '',
  ].join('\n')
}

/**
 * Write the generated source to `outputPath`. Wrapper around
 * `generateModelTypes` plus a single `fs.writeFile`.
 */
export async function writeModelTypes(
  outputPath: string,
  models: readonly PrismaModel[],
  opts: CodegenOptions = {}
): Promise<void> {
  const source = generateModelTypes(models, opts)
  await writeFile(outputPath, source, 'utf8')
}
